name: capstone_001233960 #Environment name
dependencies:
  - python=3.8
  - pip:
    - gunicorn==20.1.0 # for app deployment
    - pandas==1.3.0
    - numpy==1.21.0
    - flask==2.0.1
    - flask-cors==3.0.10
    - flasgger==0.9.5
    - flask-marshmallow==0.14.0
    - flask-sqlalchemy==2.5.1
    - marshmallow-sqlalchemy==0.26.1
    - requests==2.26.0
    - pyjwt==2.1.0
    - uuid==1.30
    - apispec==4.7.1
    - pytest==6.2.5