name: capstone_env #Environment name
dependencies:
  - python=3.8
  - pip:
    - gunicorn # for app deployment
    - pandas
    - numpy
    - flask
    - flask-cors
    - flasgger
    - flask-marshmallow
    - flask-sqlalchemy
    - pyjwt
    - uuid
    - apispec